import Head from 'next/head'
import { StrictMode } from 'react'
import FirstSection from "../components/FirstSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StrictMode>
        <FirstSection />
      </StrictMode>
    </div>
  )
}
